# Set variables

keycloak.url: ${KEYCLOAK_URL}
keycloak.url.realm: ${KEYCLOAK_URL_REALM}
keycloak.clientId: ${KEYCLOAK_CLIENTID}
keycloak.clientSecret: ${KEYCLOAK_CLIENTSECRET}
apiKey: ${ROBOCORP_CLOUD_APIKEY}

spring:
  datasource:
    url: ${RPA_JDBC_URL:jdbc:h2:./camunda-rpa-client-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${RPA_JDBC_USER:sa}
    password: ${RPA_JDBC_PASSWORD:sa}
    driverClassName: ${RPA_JDBC_DRIVER:org.h2.Driver}
    type: com.zaxxer.hikari.HikariDataSource
    connectionTimeout: ${RPA_HIKARI_CONN_TIMEOUT:30000}
    idleTimeout: ${RPA_HIKARI_IDLE_TIMEOUT:600000}
    maximumPoolSize: ${RPA_HIKARI_MAX_POOLSIZE:10}
    validationTimeout: ${RPA_HIKARI_VALID_TIMEOUT:5000}
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  webclient:
    max-buffer-size: 20

formsflow:
  formio-enabled: ${FORMIO_ENABLED:true}
  formio:
    url: ${FORMIO_URL}
    security:
      access-token-uri: ${FORMIO_URL}/user/login
      username: ${FORMIO_USERNAME}
      password: ${FORMIO_PASSWORD}

robot:
  base-dir: ${ROBOT_BASE_DIR:}
  robot-type: ${ROBOT_TYPE:ROBOCORP_CLOUD}
  cloud:
     api-url: https://api.eu1.robocorp.com/process-v1/workspaces
     api-key: ${apiKey}


client:
  base-url: ${CAMUNDA_BPM_URL}/camunda/engine-rest # the URL pointing to the Camunda Platform Runtime REST API
  lock-duration: ${LOCK_DURATION:3000} # defines how many milliseconds the External Tasks are locked until they can be fetched again
  max-tasks: ${MAX_TASKS:10}
  disable-backoff-strategy: true
  async-response-timeout: 10000
  auth:
    client-id: ${keycloak.clientId}
    client-secret: ${keycloak.clientSecret}
    token-uri: ${keycloak.url}/auth/realms/${keycloak.url.realm}/protocol/openid-connect/token
    grant_type: client_credentials

server:
  port: 8090

logging:
  level:
    org.springframework.security: ${RPA_APP_LOG_LEVEL:error}
    org.springframework.jdbc: ${RPA_APP_LOG_LEVEL:error}
    org.camunda.bpm.client: ${RPA_APP_LOG_LEVEL:error}
    org.camunda.rpa.client: ${RPA_APP_LOG_LEVEL:error}